### ISSUE TITLE
How to build stiffness matrix in two dimensions?

### ISSUE THREAD

**Issue by thehalfspace** [jpampuero/semlab#1]
I am trying to assemble stiffness matrix as a sparse matrix in two dimensions, similar to what is shown in [one dimension](https://github.com/jpampuero/semlab/blob/master/SEMLAB/BuildMK_1d.m). 

I know the current problem calculates K.u at a local level for efficiency [as shown here](https://github.com/jpampuero/semlab/blob/8df58d77cd4d4078f12c63af2cfc1d293cd4e66a/SEMLAB/sem2d_0.m#L165), but in quasi-static problem the matrix solver is a very slow step.

I am trying to do something like this:

```
# lagrange derivatives and weights as obtained from GetGLL
H = H[:]
Ht = Ht[:]
wgll2 = wgll*wgll' 
jac = dx_dxi*dy_deta   # jacobian in 2D

kglob = zeros(nglob,nglob)

# Ke is elemental stiffness
Ke = zeros(NGLL*NGLL,NGLL*NGLL)


for i in each element in x and y:
    n = 0  # iterator
    for xe in 1:NGLL:         # loop for each spectral node within one element
        for ye in 1:NGLL:
             n = n+1
              for ng in 1:NGLL*NGLL:    # loop for shape functions
                      Ke[n,ng] += mu * wgll2[xe,ye] * jac * H[ng] * Ht[ng]

       end for ng, ye, xe

      ig = iglob[:,:,i][:]
      kglob[ig,ig] += Ke
end for i
```

This doesn't give me correct answer. I am confused due to the symmetry of shape functions in x and y.

**Comment by jpampuero** [comment]
You may find a better explanation of the operations [here](https://github.com/jpampuero/semlab/blob/8df58d77cd4d4078f12c63af2cfc1d293cd4e66a/SEMLAB/sem2d_1a.m#L166) and (for irregular grids) in [section 3.6 of my lecture notes](http://web.gps.caltech.edu/~ampuero/docs/GE263_lecture_notes.pdf).

**Comment by thehalfspace** [comment]
Thanks. The lecture notes were super helpful. I am able to assemble the stiffness as sparse matrix now.

**Comment by jpampuero** [comment]
I am glad it helped. Please consider contributing your code to semlab, if you think others can benefit from it. If you make it available somewhere else, let me know.

**Comment by thehalfspace** [comment]
I'll definitely contribute to SEMLAB once I am done testing my stuff. The multiplication (Ksparse*d) is much faster than assembling the local contributions using loop. 

I have done the sparse matrix assembly [here](https://github.com/thehalfspace/eqcycle/blob/7d11b5b3877605c45ff26d3732ddc02ef19eedb4/src/Kassemble.jl#L3). I'll try to rewrite it in matlab and submit a pr for SEMLAB.

I am working on the earthquake cycle code which I will make available on Github once it is fully functional. [Here](https://github.com/thehalfspace/eqcycle) is the prototype for now.

**Comment by jpampuero** [comment]
Great work in Julia. 
The most efficient versions we have achieved in SEMLAB so far are:
 sem2d_NewmarkA1_scec2_vectorized.m
 sem2d_NewmarkA1_scec2_vectorized_parfor.m
We have used those optimizations to model cycles too. It will be interesting to see if a sparse matrix implementation performs better in matlab. Performance comparisons may depend on the language.
